server:
  port: 8888
spring:
  application:
    name: fms-config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: http://git.trescon.com.br:3000/FMS/arquitetura.poc.ja
          searchPaths: CONFIGS/{application}
          username: ${GIT3CON_USER}
          password: ${GIT3CON_PASS}
