eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: fms-instruments
  datasource:
    password: admin
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: fms_acm_db
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: false
