eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: ${PORT:0}
spring:
  application:
    name: fms-instruments
  datasource:
    password: Manuela
    url: jdbc:oracle:thin:@oracle-scl-db:1521:xe
    username: fms_cdc_db
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
