eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: ${PORT:0}
  #port: 8082
spring:
  application:
    name: fms-oauth
  datasource:
    #url: jdbc:postgresql://localhost:5432/fms-db
    #username: postgres
    #password: admin
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: fms_acm_db
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  session:
    store-type: jdbc
    
jwt:
  expiration: 43200000
    
fms-server:
  auth:
    #providerUri: http://localhost:8082
    providerUri: http://localhost:8765/fms-oauth
    jks:
      keypass: 123456
      storepass: 123456
      alias: fms
      path: keystore/fms.jks