eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    waitTimeInMsWhenSyncEmpty: 1
    enableSelfPreservation: false
    
server:
  port: 8761
  
spring:
  application:
    name: fms-eureka-server
