eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765
spring:
  application:
    name: fms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: fms-partacct-api
          uri: lb://fms-partacct-api
          predicates:
            - Path=/fms-partacct-api/**
            
        - id: fms-accsync-api
          uri: lb://fms-accsync-api
          predicates:
            - Path=/fms-accsync-api/**
            
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0                
