server:
  port: 8765
  
spring:
  application:
    name: fms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: fms-partaccts
          uri: lb://fms-partaccts
          predicates:
            - Path=/fms-partaccts/**
            
        - id: fms-accsync
          uri: lb://fms-accsync
          predicates:
            - Path=/fms-accsync/**
        
        - id: fms-instruments
          uri: lb://fms-instruments
          predicates:
            - Path=/fms-instruments/**

  config:
    import: 
    - optional:configserver:http://config-server:8888/
  
  profiles:
    active: test
