management:
  endpoints:
    web:
      exposure:
        include: '*'
        
spring:
  application:
    name: fms-instruments
  config:
    import: 
    - optional:configserver:http://config-server:8888/
  profiles:
    active: test
