management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: fms-positions
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: dev
