spring:
  application:
    name: fms-users
  profiles:
    active: dev2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
          #jwk-set-uri: http://localhost:8082/oauth2/jwks #opcional pois é padrao
          