eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: ${PORT:0}
spring:
  application:
    name: fms-users
  datasource:
    password: admin
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: fms_acm_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
